[storage]
[storage.redis]
url = "redis://127.0.0.1:6379"

[task]
redis = "redis://127.0.0.1:6379"
maxPendingCount = 20

[faucet]
endpoint = "wss://ws.f1.testnet.manta.network"
precision = 12
assets = ['MA']

[faucet.account]
mnemonic = "faucet_mnemonic"
  
[faucet.strategy]
[faucet.strategy.normal]
amounts = [
  { asset = 'MA', amount = 2 }
]
limit = 2
frequency = ["1", "day"]

[channel]

[channel.api]
port = 3000
limit = 2
frequency = ["1", "day"]

[channel.matrix]
enable = true
token = "matrix_token"
userId = "@calamari-rockefeller:matrix.org"
limit = 2
frequency = ["1", "day"]

[channel.discord]
enable = true
activeChannelName = 'calamari-faucet'
token = "discord_token"
limit = 2
frequency = ["1", "day"]

[template]
usage = """
usage:
  !balance - get the balance of the calamari testnet faucet account.
  !drip <account_address> - send calamari testnet tokens to <account_address>.
  !faucet - display all trigger commands that calamari-rockefeller will respond to.
"""
balance = "*has a balance of ${balance}*"
success = "*sends <%= amount %>, to: <%= account %>*"

riotSuccess = """
  *sends <%= amount %>, to: <%= account %>.* <a href="https://manta-testnet.subscan.io/extrinsic/<%= tx %>">track</a>
"""

[template.error]
"COMMON_ERROR" = "<%= account %> error, maybe check request and try again..."
"PADDING_TASK_MAX" = "*feels overwhelmed.* maybe try later..."
"LIMIT" = "*remembers doling out calamari to <%= account %> not long ago.* maybe try later..."
"NO_STRATEGY" = "*fails to find a strategy*"
"CHECK_TX_FAILED" = "*fails to build extrinsic*"
"CHECK_LIMIT_FAILED" = "*fails to check limit*"
"UPDATE_LIMIT_FAILED" = "*fails to update limit*"
"INSERT_TASK_FAILED" = "*fails to insert task*"
